"""`analysis/capture_stdout.py` on real throwaway scripts."""

from __future__ import annotations

from pathlib import Path

from analysis.capture_stdout import run_and_capture


def test_stdout_is_captured_verbatim_under_a_header(tmp_path: Path, capsys) -> None:
    script = tmp_path / "report.py"
    script.write_text("print('gate 1: 4168 / 5000')\nprint('  indented  line')\n", encoding="utf-8")
    assert run_and_capture("out.md", "Report", str(script), [], tmp_path) == 0
    text = (tmp_path / "out.md").read_text(encoding="utf-8")
    assert text.startswith("# Report\n\nGenerated by `")
    assert "at git `" in text
    assert "```text\ngate 1: 4168 / 5000\n  indented  line\n```" in text
    assert "gate 1: 4168 / 5000" in capsys.readouterr().out  # echoed live too


def test_a_failing_script_writes_nothing_and_propagates_its_status(tmp_path: Path) -> None:
    script = tmp_path / "bad.py"
    script.write_text("print('partial')\nraise SystemExit(3)\n", encoding="utf-8")
    assert run_and_capture("out.md", "Bad", str(script), [], tmp_path) == 3
    assert not (tmp_path / "out.md").exists()


def test_a_note_sits_in_the_header_before_the_stdout_line(tmp_path: Path) -> None:
    script = tmp_path / "report.py"
    script.write_text("print('x')\n", encoding="utf-8")
    note = "These scenarios are counterfactuals, not the committed corpus."
    assert run_and_capture("out.md", "Report", str(script), [], tmp_path, note=note) == 0
    text = (tmp_path / "out.md").read_text(encoding="utf-8")
    head = text.split("```text")[0]
    assert note in head and head.index(note) < head.index("Verbatim stdout of")
    assert head.index("Generated by") < head.index(note)


def test_the_cli_accepts_note_before_the_positional_arguments(tmp_path: Path) -> None:
    from analysis.capture_stdout import main

    script = tmp_path / "report.py"
    script.write_text("print('y')\n", encoding="utf-8")
    assert main(["capture_stdout.py", "--note", "N1", "o.md", "T", str(script)], tmp_path) == 0
    assert "N1" in (tmp_path / "o.md").read_text(encoding="utf-8")
