"""`analysis/capture_stdout.py` on real throwaway scripts."""

from __future__ import annotations

from pathlib import Path

from analysis.capture_stdout import run_and_capture


def test_stdout_is_captured_verbatim_under_a_header(tmp_path: Path, capsys) -> None:
    script = tmp_path / "report.py"
    script.write_text("print('gate 1: 4168 / 5000')\nprint('  indented  line')\n", encoding="utf-8")
    assert run_and_capture("out.md", "Report", str(script), [], tmp_path) == 0
    text = (tmp_path / "out.md").read_text(encoding="utf-8")
    assert text.startswith("# Report\n\nGenerated by `")
    assert "at git `" in text
    assert "```text\ngate 1: 4168 / 5000\n  indented  line\n```" in text
    assert "gate 1: 4168 / 5000" in capsys.readouterr().out  # echoed live too


def test_a_failing_script_writes_nothing_and_propagates_its_status(tmp_path: Path) -> None:
    script = tmp_path / "bad.py"
    script.write_text("print('partial')\nraise SystemExit(3)\n", encoding="utf-8")
    assert run_and_capture("out.md", "Bad", str(script), [], tmp_path) == 3
    assert not (tmp_path / "out.md").exists()
