"""`analysis/paper_numbers.py` tables on small hand-built frames with hand-computed cells."""

from __future__ import annotations

import pandas as pd

from analysis.paper_numbers import base_resolution, binding, composition, gates


def outcomes() -> pd.DataFrame:
    return pd.DataFrame({
        "run_id": [1, 1, 2, 3, 1, 2, 1],
        "test_id": ["a", "b", "c", "d", "a", "c", "a"],
        "split": ["all"] * 4 + ["relaxed"] * 2 + ["strict"],
    })


INSTANCES = pd.DataFrame({
    "run_id": [1, 2, 3], "repo": ["r/j", "r/j", "r/p"], "language": ["Java", "Java", "Python"],
})


def test_composition_rows_are_n_over_d_of_the_all_split() -> None:
    text = composition(outcomes(), INSTANCES)
    assert "| all | 2 | 2 (Java, Python) | 3/3 (100.00%) | 4/4 (100.00%) | 4 |" in text
    assert "| strict | 1 | 1 (Java) | 1/3 (33.33%) | 1/4 (25.00%) | 1 |" in text
    assert "| Python | 1 | 1/3 (33.33%) | 1/4 (25.00%) | 1 |" in text  # per-language, all split
    assert "Generated by `analysis/paper_numbers.py` at git `" in text


def test_base_resolution_status_mix_and_distance_statistics() -> None:
    res = pd.DataFrame({
        "status": ["no_base", "exact", "exact", "ancestor", "exact_green"],
        "base_run_distance": [None, 0.0, 1.0, 3.0, None],
    })
    text = base_resolution(res)
    assert "no_base rate: 1/5 (20.00%)" in text
    assert "| exact | 2/5 (40.00%) |" in text
    assert "with a distance recorded: 3/4 (75.00%)" in text
    assert "| median | 1 |" in text and "| max | 3 |" in text
    assert "| 0 | 1/3 (33.33%) |" in text and "| 3 | 1/3 (33.33%) |" in text


def test_binding_splits_combined_full_and_basename_only() -> None:
    b = pd.DataFrame({
        "status": ["exact", "exact", "exact", "ambiguous", "not_found"],
        "is_fqcn_qualified": [True, True, False, False, True],
    })
    text = binding(b)
    assert "| combined (exact) | 3/5 (60.00%) |" in text
    assert "| full confidence (exact, fully-qualified class name) | 2/5 (40.00%) |" in text
    assert "| basename-only, 0.5 confidence (exact, bare class name) | 1/5 (20.00%) |" in text
    assert "| ambiguous | 1/5 (20.00%) |" in text and "| not_found | 1/5 (20.00%) |" in text


def test_gates_report_labels_and_instances_and_both_binding_figures() -> None:
    b = pd.DataFrame({"status": ["exact"] * 8 + ["not_found"] * 2,
                      "is_fqcn_qualified": [True] * 6 + [False] * 2 + [True, True]})
    text = gates(outcomes(), b)
    assert "| Gate 1 (D-44, primary): strict labels | 1/5,000 (0.02%) | >= 5,000 | NOT MET |" in text
    assert "| Gate 1 (secondary): strict instances | 1/5,000 (0.02%) | >= 5,000 | NOT MET |" in text
    assert "| Gate 1.5: combined binding | 8/10 (80.00%) | >= 70% | MET |" in text
    assert "| Gate 1.5: full-confidence binding | 6/10 (60.00%) | >= 70% | NOT MET |" in text
