"""Helpers shared by every script that writes `paper/generated/*.md`.

Deterministic by construction: no timestamps, rows in a caller-given order, and
every rate rendered as `n/d (x.xx%)`. The header names the generating script
and the git commit it ran at.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

OUT_DIR = Path("paper/generated")


def git_sha() -> str:
    """Full sha of `HEAD`, or `unknown` outside a git checkout."""
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (subprocess.CalledProcessError, OSError):
        return "unknown"


def rate(n: int, d: int) -> str:
    """Render `n/d (x.xx%)`; `n/0 (n/a)` when the denominator is empty."""
    return f"{n:,}/{d:,} ({n / d:.2%})" if d else f"{n:,}/0 (n/a)"


def header(title: str, script: str, note: str = "") -> str:
    """Document title plus the generating script and git sha."""
    lines = [f"# {title}", "", f"Generated by `{script}` at git `{git_sha()}`."]
    if note:
        lines += ["", note]
    return "\n".join(lines) + "\n"


def table(columns: list[str], rows: list[list[object]]) -> str:
    """GitHub-flavoured markdown table; cells are stringified as given."""
    out = ["| " + " | ".join(columns) + " |", "|" + "|".join("---" for _ in columns) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def write(name: str, text: str, out_dir: Path = OUT_DIR) -> Path:
    """Write `text` to `out_dir/name` (creating the directory)."""
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / name
    path.write_text(text if text.endswith("\n") else text + "\n", encoding="utf-8")
    return path
